services:
  # Исходная база данных с клиентским приложением
  mssql2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASS}
    ports:
      - "1433:1433"
    volumes:
       - ./data:/var/opt/mssql/data
       - ./backup:/backup
    restart: always


  # База данных для приложения
  postgres:
    user: root
    image: postgres:16.3
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: ${POSTGRESQL_USER}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    restart: always


networks:
  default:


