services:
  # Исходная база данных с клиентским приложением
  mssql2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Irkutsk2020!"
    ports:
      - "1433:1433"
    volumes:
       - ./data:/var/opt/mssql/data
       - ./backup:/backup
    restart: always


  # Клиентское приложение PersonalAccount
  personal-account-client:
    build:
      context: ..
      dockerfile: Dockerfile
    image:  personal-account-client
    container_name:  personal-account-client
    volumes:
       - ./client.appsettings.json:/src/release/appsettings.json

  # База данных для приложения
  postgres:
    user: root
    image: postgres:16.3
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: ${POSTGRESQL_USER}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT:-5433}:5433"
    restart: always


networks:
  default:


